name: mod
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.12
  - pytorch:pytorch
  - conda-forge:pandas
  - conda-forge:opencv
  - conda-forge:matplotlib
  - conda-forge:requests
  - conda-forge:pandas
  - pip
